import { NextPage } from "next";
import Head from "next/head";
import { HTMLAttributes } from "react";
import { I18n } from "../../atoms/i18n";
import Footer from "../../organisms/footer";
import Header from "../../organisms/header";

interface Props extends HTMLAttributes<HTMLDivElement> {}

const Main: NextPage<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Miguel Buca - Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
      </Head>
      <main className="fixed overflow-y-auto scroll-smooth left-0 top-0 h-full w-full dark:bg-[#141414] dark:text-white">
        <Header />
        <div className="container md:container md:mx-auto">
          {children}
          <I18n />
        </div>
        <Footer />
      </main>
    </>
  );
};

export default Main;
