import { NextPage } from 'next'
import Head from 'next/head';
import { HTMLAttributes } from 'react';
import Footer from '../../organisms/footer';
import Header from '../../organisms/header';

interface Props{
  url: string
}

const Frame: NextPage<Props> = ({ url }) => {
  return (
    <>
      <Head>
        <title>Miguel Buca - Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="fixed overflow-y-auto scroll-smooth left-0 top-0 h-full w-full bg-[#141414] text-white">
        <Header />
        <iframe src={url} frameBorder="0" className='w-full h-full'/>
      </main>
    </>
  );
};

export default Frame