import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import prismicClient from '../src/services/prismic';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline text-blue-500">Hello world!</h1>
      </main>
    </div>
  );
}

export default Home

export const getStaticProps: GetStaticProps = async () => {

  /*const projectResponse = await prismic.query(
    [prismic.predicate.at("document.type", "portfolio-custom-type")],
    { orderings: "[document.createdAt desc]" }
  );*/

  console.log(await prismicClient().getByType("portfolio-custom-type"));

  return {
    props: {},
    revalidate: 86400,
  };
};